# SCREEN_HEIGHT=2160
# SCREEN_WIDTH=3840

# INTERNAL_WIDTH=1280
# INTERNAL_HEIGHT=800

# Set priority of display connectors
# OUTPUT_CONNECTOR='*,DSI-1'

# Set the target luminace of the inverse tone mapping process (optional)
# GAMESCOPE_HDR_NITS=400
