name: COPR release

on:
  workflow_dispatch:

jobs:
  COPR_build:
    uses: pvermeer/rpm-tools/.github/workflows/copr-release.yml@main
    with:
      spec_file: ./gamescope-session-steam.spec
      copr_owner: pvermeer
      copr_project: gamescope-session-steam
      copr_package: gamescope-session-steam
    permissions:
      contents: write
    secrets:
      COPR_WEBHOOK: ${{ secrets.COPR_WEBHOOK }}
